/**
 * Created by meteor on 16/11/25.
 */
module.exports= [ { code: 'en-US',
    type: 'forgotPwdMsg',
    sign: ' [pictureAir] ',
    content: '<!DOCTYPE html> <html lang="en"><head><meta charset="UTF-8"><title>Title</title></head><body>Dear Guest,<br><br>We have received your request of password resetting.<br><br>Please click the link below.<br><br><a href="http://www.disneyphotopass.com.cn/forgotPwd.html?v=%validateCode%">http://www.disneyphotopass.com.cn/forgotPwd.html?v=%validateCode%</a><br><br>We suggest that you should reset your password after you enter the provided link in this email for easier accessing to your account in the future.<br><br> Therefore, please visit this Disney PhotoPass website :<br><br><a href="http://www.disneyphotopass.com.cn/">http://www.disneyphotopass.com.cn/</a><br><br>Furthermore, please visit our “Help” section for updates and more information of our services and products.<br><br>Thank you!<br><br>Disney PhotoPass<br><br>This email is generated by system, so please do not relpy.<br><br>If you have other questions or comments, or if you believe you have received this message in error, please do not reply to this email. Instead, visit our Help section where you can find the answers you need.</body></html>' },
    { code: 'zh-CN',
        type: 'forgotPwdMsg',
        sign: '【相集】',
        content: '<!DOCTYPE html> <html lang="en"><head><meta charset="UTF-8"><title>Title</title></head><body>尊敬的用户,<br><br> 我们已收到您重置密码的请求。<br><br> 请点击一下链接重设您的密码：<br><br><a href="http://www.disneyphotopass.com.cn/forgotPwd.html?v=%validateCode%">http://www.disneyphotopass.com.cn/forgotPwd.html?v=%validateCode%</a><br><br>我们建议您在使用本电子邮件提供的链接登录之后，对密码进行更改，以便将来更轻松地访问您的账户。<br><br>为此，请访问迪士尼乐拍通官网：<br><br><a href="http://www.disneyphotopass.com.cn/">http://www.disneyphotopass.com.cn/</a><br><br>另外，请访问 帮助 获取有关我们的服务和产品的更新和其它信息。<br><br>谢谢！<br><br>迪士尼乐拍通<br><br>此电子邮件由系统生成，请勿回复。<br><br>如果您有其它问题或意见，或者您误收到此邮件，请勿回复。请访问帮助，在这里可以解决您所有的疑问。<br><br> </body></html>' },
    { code: 'en-US',
        type: 'forgotPwdMsg_test',
        sign: ' [pictureAir] ',
        content: '<!DOCTYPE html> <html lang="en"><head><meta charset="UTF-8"><title>Title</title></head><body>Dear Guest,<br><br>We have received your request of password resetting.<br><br>Please click the link below.<br><br><a href="http://192.168.8.107/#/?v=%validateCode%">http://192.168.8.107/#/?v=%validateCode%</a><br><br>We suggest that you should reset your password after you enter the provided link in this email for easier accessing to your account in the future.<br><br> Therefore, please visit this Disney PhotoPass website :<br><br><a href="http://192.168.8.107/">http://192.168.8.107/</a><br><br>Furthermore, please visit our “Help” section for updates and more information of our services and products.<br><br>Thank you!<br><br>Disney PhotoPass<br><br>This email is generated by system, so please do not relpy.<br><br>If you have other questions or comments, or if you believe you have received this message in error, please do not reply to this email. Instead, visit our Help section where you can find the answers you need.</body></html>' },
    { code: 'zh-CN',
        type: 'forgotPwdMsg_test',
        sign: '【相集】',
        content: '<!DOCTYPE html> <html lang="en"><head><meta charset="UTF-8"><title>Title</title></head><body>尊敬的用户,<br><br> 我们已收到您重置密码的请求。<br><br> 请点击一下链接重设您的密码：<br><br><a href="http://192.168.8.107/#/?v=%validateCode%">http://192.168.8.107/#/?v=%validateCode%</a><br><br>我们建议您在使用本电子邮件提供的链接登录之后，对密码进行更改，以便将来更轻松地访问您的账户。<br><br>为此，请访问迪士尼乐拍通官网：<br><br><a href="http://192.168.8.107/">http://192.168.8.107/</a><br><br>另外，请访问 帮助 获取有关我们的服务和产品的更新和其它信息。<br><br>谢谢！<br><br>迪士尼乐拍通<br><br>此电子邮件由系统生成，请勿回复。<br><br>如果您有其它问题或意见，或者您误收到此邮件，请勿回复。请访问帮助，在这里可以解决您所有的疑问。<br><br> </body></html>' }
]
