/**
 * Created by meteor on 16/11/25.
 */
module.exports= [
    { code: 'en-US',
    type: 'forgotPwdMsg',
    sign: ' [PictureAir Password Reset] ',
    content:  '<!DOCTYPE html> <html lang="en"><head><meta charset="UTF-8"><title>Title</title></head><body>Dear Guest, <br><br>We have received the request to reset your password.<br><br>If you did not request for a password reset, please ignore this email, otherwise, please click the link below.<br><br><a href="http://web.pictureair.com/#/?v=%validateCode%">http://web.pictureair.com/#/?v=%validateCode%</a><br><br>We suggest that you should change your password after you enter the provided link in this email for easier access to your account in the future.<br><br> For more information, please visit the PictureAir website :<br><br><a href="http://web.pictureair.com/">http://web.pictureair.com/</a><br><br><br><br>Thank you!<br><br>PictureAir<br><br>This is a system generated email, please do not reply.<br><br>If you have other questions or comments, or if you believe you have received this message in error, please do not reply to this email. Instead, visit our FAQ section where you can find the answers you need.</body></html>'
    },
    { code: 'zh-CN',
        type: 'forgotPwdMsg',
        sign: '【相集 重置密码】',
        content: '<!DOCTYPE html> <html lang="en"><head><meta charset="UTF-8"><title>Title</title></head><body>尊敬的用户,<br><br> 我们已收到您重置密码的请求。<br><br> 如果你并没有请求重置密码，请忽略这封电子邮件，否则请点击以下链接重设您的密码：<br><br><a href="http://web.pictureair.com/#/?v=%validateCode%">http://web.pictureair.com/#/?v=%validateCode%</a><br><br>我们建议您在使用本电子邮件提供的链接登录之后，对密码进行更改，以便将来更轻松地访问您的账户。<br><br>为此，请访问相集官网：<br><br><a href="http://web.pictureari.com/">http://web.pictureair.com/</a><br><br><br><br>谢谢！<br><br>相集<br><br>此电子邮件由系统生成，请勿回复。<br><br>如果您有其它问题或意见，或者您误收到此邮件，请勿回复。请访问帮助，在这里可以解决您所有的疑问。<br><br> </body></html>'
    },
    { code: 'en-US',
        type: 'forgotPwdMsg_test',
        sign: ' [pictureAir] ',
        content: '<!DOCTYPE html> <html lang="en"><head><meta charset="UTF-8"><title>Title</title></head><body>Dear Guest,<br><br>We have received your request of password resetting.<br><br>Please click the link below.<br><br><a href="http://192.168.8.107/#/?v=%validateCode%">http://192.168.8.107/#/?v=%validateCode%</a><br><br>We suggest that you should reset your password after you enter the provided link in this email for easier accessing to your account in the future.<br><br> Therefore, please visit this Disney PhotoPass website :<br><br><a href="http://192.168.8.107/">http://192.168.8.107/</a><br><br>Furthermore, please visit our “Help” section for updates and more information of our services and products.<br><br>Thank you!<br><br>Disney PhotoPass<br><br>This email is generated by system, so please do not relpy.<br><br>If you have other questions or comments, or if you believe you have received this message in error, please do not reply to this email. Instead, visit our Help section where you can find the answers you need.</body></html>' },
    { code: 'zh-CN',
        type: 'forgotPwdMsg_test',
        sign: '【相集】',
        content: '<!DOCTYPE html> <html lang="en"><head><meta charset="UTF-8"><title>Title</title></head><body>尊敬的用户,<br><br> 我们已收到您重置密码的请求。<br><br> 请点击一下链接重设您的密码：<br><br><a href="http://192.168.8.107/#/?v=%validateCode%">http://192.168.8.107/#/?v=%validateCode%</a><br><br>我们建议您在使用本电子邮件提供的链接登录之后，对密码进行更改，以便将来更轻松地访问您的账户。<br><br>为此，请访问迪士尼乐拍通官网：<br><br><a href="http://192.168.8.107/">http://192.168.8.107/</a><br><br>另外，请访问 帮助 获取有关我们的服务和产品的更新和其它信息。<br><br>谢谢！<br><br>迪士尼乐拍通<br><br>此电子邮件由系统生成，请勿回复。<br><br>如果您有其它问题或意见，或者您误收到此邮件，请勿回复。请访问帮助，在这里可以解决您所有的疑问。<br><br> </body></html>' },
    { code: 'en-US',
        type: 'contactUs',
        sign: ' [pictureAir] ',
        content: '<!DOCTYPE html> <html lang="en"><head><meta charset="UTF-8"><title>Title</title></head><body>Hi, <br><br> The guest enquiry is as followed:<br><br>msgid ：%msgid%<br><br>Name: %name%<br><br>Email Address: %EmailAddress%<br><br>Park / Attraction Name: %parkName%<br><br>Date of Visit: %visitDate%<br><br>PictureAir Code: %pictureAirCode%<br><br>Order ID: %orderID%<br><br>Operating System: %operatingSystem%<br><br> Feedback: %feedback%<br><br></body></html>' },
    { code: 'zh-CN',
        type: 'contactUs',
        sign: '【相集】',
        content: '<!DOCTYPE html> <html lang="en"><head><meta charset="UTF-8"><title>Title</title></head><body>亲爱的同事， <br><br> 以下是我们客户需要解决的问题。<br><br>msgid ：%msgid%<br><br>姓名 ：%name%<br><br>电子邮件 ：%EmailAddress%<br><br>乐园／景点名字 ：%parkName%<br><br>入园日期 ：%visitDate%<br><br>相集卡编码 ：%pictureAirCode%<br><br>订单编码 ：%orderID%<br><br>操作系统 ：%operatingSystem%<br><br> 描述 ：%feedback%<br><br></body></html>' }
]
